a = input ("Digite algo")
print(a.isalpha())
print(a.isalnum())
print(a.isascii())
print(a.isdecimal())
print(a.isdigit())
print(a.isidentifier())
print(a.islower())
print(a.isprintable())
print(a.isspace())
print(a.istitle())
print(a.isupper())
